/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ArchiveRouteImport } from './routes/archive'
import { Route as ChronicleRouteImport } from './routes/chronicle'
import { Route as CircleRouteImport } from './routes/circle'
import { Route as CredRouteImport } from './routes/cred'
import { Route as CustomRouteImport } from './routes/custom'
import { Route as EventsRouteImport } from './routes/events'
import { Route as HouseRouteImport } from './routes/house'
import { Route as MekhkRouteImport } from './routes/mekhk'
import { Route as NetworkRouteImport } from './routes/network'
import { Route as ReferralsRouteImport } from './routes/referrals'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SilsilaRouteImport } from './routes/silsila'
import { Route as TokenRouteImport } from './routes/token'
import { Route as WalletRouteImport } from './routes/wallet'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchiveRoute = ArchiveRouteImport.update({
  id: '/archive',
  path: '/archive',
  getParentRoute: () => rootRouteImport,
} as any)
const ChronicleRoute = ChronicleRouteImport.update({
  id: '/chronicle',
  path: '/chronicle',
  getParentRoute: () => rootRouteImport,
} as any)
const CircleRoute = CircleRouteImport.update({
  id: '/circle',
  path: '/circle',
  getParentRoute: () => rootRouteImport,
} as any)
const CredRoute = CredRouteImport.update({
  id: '/cred',
  path: '/cred',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomRoute = CustomRouteImport.update({
  id: '/custom',
  path: '/custom',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const HouseRoute = HouseRouteImport.update({
  id: '/house',
  path: '/house',
  getParentRoute: () => rootRouteImport,
} as any)
const MekhkRoute = MekhkRouteImport.update({
  id: '/mekhk',
  path: '/mekhk',
  getParentRoute: () => rootRouteImport,
} as any)
const NetworkRoute = NetworkRouteImport.update({
  id: '/network',
  path: '/network',
  getParentRoute: () => rootRouteImport,
} as any)
const ReferralsRoute = ReferralsRouteImport.update({
  id: '/referrals',
  path: '/referrals',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SilsilaRoute = SilsilaRouteImport.update({
  id: '/silsila',
  path: '/silsila',
  getParentRoute: () => rootRouteImport,
} as any)
const TokenRoute = TokenRouteImport.update({
  id: '/token',
  path: '/token',
  getParentRoute: () => rootRouteImport,
} as any)
const WalletRoute = WalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/archive': typeof ArchiveRoute
  '/chronicle': typeof ChronicleRoute
  '/circle': typeof CircleRoute
  '/cred': typeof CredRoute
  '/custom': typeof CustomRoute
  '/events': typeof EventsRoute
  '/house': typeof HouseRoute
  '/mekhk': typeof MekhkRoute
  '/network': typeof NetworkRoute
  '/referrals': typeof ReferralsRoute
  '/settings': typeof SettingsRoute
  '/silsila': typeof SilsilaRoute
  '/token': typeof TokenRoute
  '/wallet': typeof WalletRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/archive': typeof ArchiveRoute
  '/chronicle': typeof ChronicleRoute
  '/circle': typeof CircleRoute
  '/cred': typeof CredRoute
  '/custom': typeof CustomRoute
  '/events': typeof EventsRoute
  '/house': typeof HouseRoute
  '/mekhk': typeof MekhkRoute
  '/network': typeof NetworkRoute
  '/referrals': typeof ReferralsRoute
  '/settings': typeof SettingsRoute
  '/silsila': typeof SilsilaRoute
  '/token': typeof TokenRoute
  '/wallet': typeof WalletRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/archive': typeof ArchiveRoute
  '/chronicle': typeof ChronicleRoute
  '/circle': typeof CircleRoute
  '/cred': typeof CredRoute
  '/custom': typeof CustomRoute
  '/events': typeof EventsRoute
  '/house': typeof HouseRoute
  '/mekhk': typeof MekhkRoute
  '/network': typeof NetworkRoute
  '/referrals': typeof ReferralsRoute
  '/settings': typeof SettingsRoute
  '/silsila': typeof SilsilaRoute
  '/token': typeof TokenRoute
  '/wallet': typeof WalletRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/archive'
    | '/chronicle'
    | '/circle'
    | '/cred'
    | '/custom'
    | '/events'
    | '/house'
    | '/mekhk'
    | '/network'
    | '/referrals'
    | '/settings'
    | '/silsila'
    | '/token'
    | '/wallet'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/archive'
    | '/chronicle'
    | '/circle'
    | '/cred'
    | '/custom'
    | '/events'
    | '/house'
    | '/mekhk'
    | '/network'
    | '/referrals'
    | '/settings'
    | '/silsila'
    | '/token'
    | '/wallet'
  id:
    | '__root__'
    | '/'
    | '/archive'
    | '/chronicle'
    | '/circle'
    | '/cred'
    | '/custom'
    | '/events'
    | '/house'
    | '/mekhk'
    | '/network'
    | '/referrals'
    | '/settings'
    | '/silsila'
    | '/token'
    | '/wallet'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArchiveRoute: typeof ArchiveRoute
  ChronicleRoute: typeof ChronicleRoute
  CircleRoute: typeof CircleRoute
  CredRoute: typeof CredRoute
  CustomRoute: typeof CustomRoute
  EventsRoute: typeof EventsRoute
  HouseRoute: typeof HouseRoute
  MekhkRoute: typeof MekhkRoute
  NetworkRoute: typeof NetworkRoute
  ReferralsRoute: typeof ReferralsRoute
  SettingsRoute: typeof SettingsRoute
  SilsilaRoute: typeof SilsilaRoute
  TokenRoute: typeof TokenRoute
  WalletRoute: typeof WalletRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/archive': {
      id: '/archive'
      path: '/archive'
      fullPath: '/archive'
      preLoaderRoute: typeof ArchiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chronicle': {
      id: '/chronicle'
      path: '/chronicle'
      fullPath: '/chronicle'
      preLoaderRoute: typeof ChronicleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/circle': {
      id: '/circle'
      path: '/circle'
      fullPath: '/circle'
      preLoaderRoute: typeof CircleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cred': {
      id: '/cred'
      path: '/cred'
      fullPath: '/cred'
      preLoaderRoute: typeof CredRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/custom': {
      id: '/custom'
      path: '/custom'
      fullPath: '/custom'
      preLoaderRoute: typeof CustomRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/house': {
      id: '/house'
      path: '/house'
      fullPath: '/house'
      preLoaderRoute: typeof HouseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mekhk': {
      id: '/mekhk'
      path: '/mekhk'
      fullPath: '/mekhk'
      preLoaderRoute: typeof MekhkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/network': {
      id: '/network'
      path: '/network'
      fullPath: '/network'
      preLoaderRoute: typeof NetworkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/referrals': {
      id: '/referrals'
      path: '/referrals'
      fullPath: '/referrals'
      preLoaderRoute: typeof ReferralsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/silsila': {
      id: '/silsila'
      path: '/silsila'
      fullPath: '/silsila'
      preLoaderRoute: typeof SilsilaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/token': {
      id: '/token'
      path: '/token'
      fullPath: '/token'
      preLoaderRoute: typeof TokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wallet': {
      id: '/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof WalletRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArchiveRoute: ArchiveRoute,
  ChronicleRoute: ChronicleRoute,
  CircleRoute: CircleRoute,
  CredRoute: CredRoute,
  CustomRoute: CustomRoute,
  EventsRoute: EventsRoute,
  HouseRoute: HouseRoute,
  MekhkRoute: MekhkRoute,
  NetworkRoute: NetworkRoute,
  ReferralsRoute: ReferralsRoute,
  SettingsRoute: SettingsRoute,
  SilsilaRoute: SilsilaRoute,
  TokenRoute: TokenRoute,
  WalletRoute: WalletRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
